[package]
name = "zproto"
version = "0.4.3-pre"
authors = ["Stephen Hunt <stphnhnt.git@gmail.com>"]
edition = "2021"
description = "A library from communicating with Zaber products in Rust."
license = "MIT"
readme = "README.md"
repository = "https://github.com/stphnt/zproto"
documentation = "https://docs.rs/zproto"
homepage = "https://github.com/stphnt/zproto"
keywords = ["Zaber", "ASCII", "Binary", "serial", "RS232"]
categories = ["hardware-support"]
include = [
    "examples/",
    "src/",
    "test/",
    "LICENSE",
    "README.md",
]

[package.metadata.docs.rs]
all-features = true

[workspace]
members = ["scripts/generate-apis"]

[features]
default = ["ascii", "binary"]
ascii = [] # Include the ASCII protocol
binary = [] # Include the Binary protocol
mock = [] # Include the Mock backend, for use in consuming crate tests

# Use the nightly-only `doc_cfg` feature when generating the documentation.
doc_cfg = []

[dependencies]
log = "0.4.19"
paste = "1.0.12"
serialport = "4.7.0"

[dev-dependencies]
simple_logger = "5.0.0"
static_assertions = "1.1.0"

[[example]]
name = "ascii"
required-features = ["ascii"]

[[example]]
name = "binary"
required-features = ["binary"]

[lints.clippy]
cargo = { level = "deny", priority = -1 }
# Some dependencies each have common dependencies but with different versions
# We cannot fix this, so ignore the lint.
multiple_crate_versions = "allow"

pedantic = { level = "deny", priority = -1 }
# Pedantic group overrides
module_name_repetitions = "allow"
must_use_candidate = "allow" # too many
missing_errors_doc = "allow"
missing_panics_doc = "allow"
needless_pass_by_value = "allow"

[lints.rust]
# groups
warnings = { level = "deny", priority = -1 }
rust-2018-idioms = { level = "deny", priority = -1 }

# individual lints
missing-docs = "deny"
macro-use-extern-crate = "deny"
meta-variable-misuse = "deny"
missing-debug-implementations = "deny"
non-local-definitions = "deny"
redundant-lifetimes = "deny"
unit-bindings = "deny"
unsafe-op-in-unsafe-fn = "deny"
unused-lifetimes = "deny"

unexpected_cfgs = { level = "deny", check-cfg = ['cfg(unstable)'] }

[lints.rustdoc]
missing-crate-level-docs = "deny"
unescaped-backticks = "deny"

