[workspace]
members = [
    "scripts/generate-apis",
    "zproto",
]
resolver = "2"

[workspace.lints.clippy]
cargo = { level = "deny", priority = -1 }
# Some dependencies each have common dependencies but with different versions
# We cannot fix this, so ignore the lint.
multiple_crate_versions = "allow"

pedantic = { level = "deny", priority = -1 }
# Pedantic group overrides
module_name_repetitions = "allow"
must_use_candidate = "allow" # too many
missing_errors_doc = "allow"
missing_panics_doc = "allow"
needless_pass_by_value = "allow"

[workspace.lints.rust]
# groups
warnings = { level = "deny", priority = -1 }
rust-2018-idioms = { level = "deny", priority = -1 }

# individual lints
missing-docs = "deny"
macro-use-extern-crate = "deny"
meta-variable-misuse = "deny"
missing-debug-implementations = "deny"
non-local-definitions = "deny"
redundant-lifetimes = "deny"
unit-bindings = "deny"
unsafe-op-in-unsafe-fn = "deny"
unused-lifetimes = "deny"

unexpected_cfgs = { level = "deny", check-cfg = ['cfg(unstable)'] }

[workspace.lints.rustdoc]
missing-crate-level-docs = "deny"
unescaped-backticks = "deny"

